### ISSUE TITLE
Bug: missing crates that have crate links in the markdown

### ISSUE THREAD

**Issue by joshka** [emanuelef/awesome-rust-repo-stats#45]
From https://github.com/rust-unofficial/awesome-rust/blob/main/CONTRIBUTING.md:
> if you want to add something, please use the template `[ACCOUNT/REPO](https://github.com/ACCOUNT/REPO) [[CRATE](https://crates.io/crates/CRATE)] — DESCRIPTION` 

The current regex:

```go
exp := regexp.MustCompile(`\* \[([^\]]+)]\(https:\/\/github\.com\/([^\/\s]+\/[^\/\s]+)\) - .*`)
```

E.g. the entire cli section has a single entry.

Perhaps it would be worth just matching any github repo and ignoring the other parts of the line entirely for the purposes of matching?

**Comment by joshka** [comment]
Note that the format is now using an emdash `—` instead of a dash `-`

**Comment by emanuelef** [comment]
@joshka thanks for reporting that, sorry I missed this.
Let me have a look and see how it can be fixed.

**Comment by joshka** [comment]
No problem. The Ratatui crate (ratatui-org/ratatui on github) is the reason I saw this - it doesn't show up in any category. The awesome rust repo has since moved back to using ordinary dashes instead of em-dashes.

**Comment by emanuelef** [comment]
@joshka the issue should have been fixed now, thanks for pointing that out the repos parsed are now 1048 compared to the 799 before the fix.

**Comment by joshka** [comment]
Neat! thanks
